(cl:defpackage franka_interface_msgs-srv
  (:use )
  (:export
   "GETCURRENTFRANKAINTERFACESTATUSCMD"
   "<GETCURRENTFRANKAINTERFACESTATUSCMD-REQUEST>"
   "GETCURRENTFRANKAINTERFACESTATUSCMD-REQUEST"
   "<GETCURRENTFRANKAINTERFACESTATUSCMD-RESPONSE>"
   "GETCURRENTFRANKAINTERFACESTATUSCMD-RESPONSE"
   "GETCURRENTROBOTSTATECMD"
   "<GETCURRENTROBOTSTATECMD-REQUEST>"
   "GETCURRENTROBOTSTATECMD-REQUEST"
   "<GETCURRENTROBOTSTATECMD-RESPONSE>"
   "GETCURRENTROBOTSTATECMD-RESPONSE"
  ))

