# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmdRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetCurrentFrankaInterfaceStatusCmdRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmdRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetCurrentFrankaInterfaceStatusCmdRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmdResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import franka_interface_msgs.msg
import std_msgs.msg

class GetCurrentFrankaInterfaceStatusCmdResponse(genpy.Message):
  _md5sum = "1d3fe55393993751ebdd77c7f87c1d1e"
  _type = "franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmdResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """FrankaInterfaceStatus franka_interface_status

================================================================================
MSG: franka_interface_msgs/FrankaInterfaceStatus
# Franka robot state
std_msgs/Header header
bool is_ready
string error_description
bool is_fresh
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['franka_interface_status']
  _slot_types = ['franka_interface_msgs/FrankaInterfaceStatus']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       franka_interface_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetCurrentFrankaInterfaceStatusCmdResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.franka_interface_status is None:
        self.franka_interface_status = franka_interface_msgs.msg.FrankaInterfaceStatus()
    else:
      self.franka_interface_status = franka_interface_msgs.msg.FrankaInterfaceStatus()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.franka_interface_status.header.seq, _x.franka_interface_status.header.stamp.secs, _x.franka_interface_status.header.stamp.nsecs))
      _x = self.franka_interface_status.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.franka_interface_status.is_ready
      buff.write(_get_struct_B().pack(_x))
      _x = self.franka_interface_status.error_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.franka_interface_status.is_fresh
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.franka_interface_status is None:
        self.franka_interface_status = franka_interface_msgs.msg.FrankaInterfaceStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.franka_interface_status.header.seq, _x.franka_interface_status.header.stamp.secs, _x.franka_interface_status.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.franka_interface_status.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.franka_interface_status.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.franka_interface_status.is_ready,) = _get_struct_B().unpack(str[start:end])
      self.franka_interface_status.is_ready = bool(self.franka_interface_status.is_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.franka_interface_status.error_description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.franka_interface_status.error_description = str[start:end]
      start = end
      end += 1
      (self.franka_interface_status.is_fresh,) = _get_struct_B().unpack(str[start:end])
      self.franka_interface_status.is_fresh = bool(self.franka_interface_status.is_fresh)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.franka_interface_status.header.seq, _x.franka_interface_status.header.stamp.secs, _x.franka_interface_status.header.stamp.nsecs))
      _x = self.franka_interface_status.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.franka_interface_status.is_ready
      buff.write(_get_struct_B().pack(_x))
      _x = self.franka_interface_status.error_description
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.franka_interface_status.is_fresh
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.franka_interface_status is None:
        self.franka_interface_status = franka_interface_msgs.msg.FrankaInterfaceStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.franka_interface_status.header.seq, _x.franka_interface_status.header.stamp.secs, _x.franka_interface_status.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.franka_interface_status.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.franka_interface_status.header.frame_id = str[start:end]
      start = end
      end += 1
      (self.franka_interface_status.is_ready,) = _get_struct_B().unpack(str[start:end])
      self.franka_interface_status.is_ready = bool(self.franka_interface_status.is_ready)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.franka_interface_status.error_description = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.franka_interface_status.error_description = str[start:end]
      start = end
      end += 1
      (self.franka_interface_status.is_fresh,) = _get_struct_B().unpack(str[start:end])
      self.franka_interface_status.is_fresh = bool(self.franka_interface_status.is_fresh)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class GetCurrentFrankaInterfaceStatusCmd(object):
  _type          = 'franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmd'
  _md5sum = '1d3fe55393993751ebdd77c7f87c1d1e'
  _request_class  = GetCurrentFrankaInterfaceStatusCmdRequest
  _response_class = GetCurrentFrankaInterfaceStatusCmdResponse
