// Generated by gencpp from file franka_interface_msgs/ExecuteSkillActionGoal.msg
// DO NOT EDIT!


#ifndef FRANKA_INTERFACE_MSGS_MESSAGE_EXECUTESKILLACTIONGOAL_H
#define FRANKA_INTERFACE_MSGS_MESSAGE_EXECUTESKILLACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <franka_interface_msgs/ExecuteSkillGoal.h>

namespace franka_interface_msgs
{
template <class ContainerAllocator>
struct ExecuteSkillActionGoal_
{
  typedef ExecuteSkillActionGoal_<ContainerAllocator> Type;

  ExecuteSkillActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ExecuteSkillActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::franka_interface_msgs::ExecuteSkillGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteSkillActionGoal_

typedef ::franka_interface_msgs::ExecuteSkillActionGoal_<std::allocator<void> > ExecuteSkillActionGoal;

typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillActionGoal > ExecuteSkillActionGoalPtr;
typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillActionGoal const> ExecuteSkillActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator1> & lhs, const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator1> & lhs, const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_interface_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9010c44dae6748cc80ceac2c2cce6e13";
  }

  static const char* value(const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9010c44dae6748ccULL;
  static const uint64_t static_value2 = 0x80ceac2c2cce6e13ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_interface_msgs/ExecuteSkillActionGoal";
  }

  static const char* value(const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ExecuteSkillGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: franka_interface_msgs/ExecuteSkillGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint8 skill_type\n"
"string skill_description\n"
"uint8 meta_skill_type\n"
"int64 meta_skill_id\n"
"\n"
"# Sensor topic to subscribe to\n"
"string[] sensor_topics\n"
"uint64[] sensor_value_sizes\n"
"float64[] initial_sensor_values\n"
"\n"
"# traj gen\n"
"uint8 trajectory_generator_type\n"
"int32 trajectory_generator_param_data_size\n"
"uint8[] trajectory_generator_param_data\n"
"\n"
"# fbc\n"
"uint8 feedback_controller_type\n"
"int32 feedback_controller_param_data_size\n"
"uint8[] feedback_controller_param_data\n"
"\n"
"# termination\n"
"uint8 termination_handler_type\n"
"int32 termination_handler_param_data_size\n"
"uint8[] termination_handler_param_data \n"
"\n"
"# timer\n"
"uint8 timer_type\n"
"int32 num_timer_params\n"
"uint8[] timer_params\n"
;
  }

  static const char* value(const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteSkillActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_interface_msgs::ExecuteSkillActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::franka_interface_msgs::ExecuteSkillGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_INTERFACE_MSGS_MESSAGE_EXECUTESKILLACTIONGOAL_H
