// Generated by gencpp from file franka_interface_msgs/FrankaInterfaceStatus.msg
// DO NOT EDIT!


#ifndef FRANKA_INTERFACE_MSGS_MESSAGE_FRANKAINTERFACESTATUS_H
#define FRANKA_INTERFACE_MSGS_MESSAGE_FRANKAINTERFACESTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace franka_interface_msgs
{
template <class ContainerAllocator>
struct FrankaInterfaceStatus_
{
  typedef FrankaInterfaceStatus_<ContainerAllocator> Type;

  FrankaInterfaceStatus_()
    : header()
    , is_ready(false)
    , error_description()
    , is_fresh(false)  {
    }
  FrankaInterfaceStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_ready(false)
    , error_description(_alloc)
    , is_fresh(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_ready_type;
  _is_ready_type is_ready;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_description_type;
  _error_description_type error_description;

   typedef uint8_t _is_fresh_type;
  _is_fresh_type is_fresh;





  typedef boost::shared_ptr< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> const> ConstPtr;

}; // struct FrankaInterfaceStatus_

typedef ::franka_interface_msgs::FrankaInterfaceStatus_<std::allocator<void> > FrankaInterfaceStatus;

typedef boost::shared_ptr< ::franka_interface_msgs::FrankaInterfaceStatus > FrankaInterfaceStatusPtr;
typedef boost::shared_ptr< ::franka_interface_msgs::FrankaInterfaceStatus const> FrankaInterfaceStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator1> & lhs, const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_ready == rhs.is_ready &&
    lhs.error_description == rhs.error_description &&
    lhs.is_fresh == rhs.is_fresh;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator1> & lhs, const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_interface_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3b55f2e82de58761423a010b7b229a0";
  }

  static const char* value(const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3b55f2e82de5876ULL;
  static const uint64_t static_value2 = 0x1423a010b7b229a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_interface_msgs/FrankaInterfaceStatus";
  }

  static const char* value(const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Franka robot state\n"
"std_msgs/Header header\n"
"bool is_ready\n"
"string error_description\n"
"bool is_fresh\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_ready);
      stream.next(m.error_description);
      stream.next(m.is_fresh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrankaInterfaceStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_interface_msgs::FrankaInterfaceStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_ready);
    s << indent << "error_description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_description);
    s << indent << "is_fresh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_fresh);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_INTERFACE_MSGS_MESSAGE_FRANKAINTERFACESTATUS_H
