(cl:in-package franka_interface_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HAS_TRAJECTORY_GENERATOR_SENSOR_DATA-VAL
          HAS_TRAJECTORY_GENERATOR_SENSOR_DATA
          HAS_FEEDBACK_CONTROLLER_SENSOR_DATA-VAL
          HAS_FEEDBACK_CONTROLLER_SENSOR_DATA
          HAS_TERMINATION_HANDLER_SENSOR_DATA-VAL
          HAS_TERMINATION_HANDLER_SENSOR_DATA
          TRAJECTORYGENERATORSENSORDATA-VAL
          TRAJECTORYGENERATORSENSORDATA
          FEEDBACKCONTROLLERSENSORDATA-VAL
          FEEDBACKCONTROLLERSENSORDATA
          TERMINATIONHANDLERSENSORDATA-VAL
          TERMINATIONHANDLERSENSORDATA
))