(cl:in-package franka_interface_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POSE_DESIRED-VAL
          POSE_DESIRED
          O_T_EE-VAL
          O_T_EE
          O_T_EE_D-VAL
          O_T_EE_D
          F_T_EE-VAL
          F_T_EE
          EE_T_K-VAL
          EE_T_K
          M_EE-VAL
          M_EE
          I_EE-VAL
          I_EE
          F_X_CEE-VAL
          F_X_CEE
          M_LOAD-VAL
          M_LOAD
          I_LOAD-VAL
          I_LOAD
          F_X_CLOAD-VAL
          F_X_CLOAD
          M_TOTAL-VAL
          M_TOTAL
          I_TOTAL-VAL
          I_TOTAL
          F_X_CTOTAL-VAL
          F_X_CTOTAL
          ELBOW-VAL
          ELBOW
          ELBOW_D-VAL
          ELBOW_D
          ELBOW_C-VAL
          ELBOW_C
          DELBOW_C-VAL
          DELBOW_C
          DDELBOW_C-VAL
          DDELBOW_C
          TAU_J-VAL
          TAU_J
          TAU_J_D-VAL
          TAU_J_D
          DTAU_J-VAL
          DTAU_J
          Q-VAL
          Q
          Q_D-VAL
          Q_D
          DQ-VAL
          DQ
          DQ_D-VAL
          DQ_D
          DDQ_D-VAL
          DDQ_D
          JOINT_CONTACT-VAL
          JOINT_CONTACT
          CARTESIAN_CONTACT-VAL
          CARTESIAN_CONTACT
          JOINT_COLLISION-VAL
          JOINT_COLLISION
          CARTESIAN_COLLISION-VAL
          CARTESIAN_COLLISION
          TAU_EXT_HAT_FILTERED-VAL
          TAU_EXT_HAT_FILTERED
          O_F_EXT_HAT_K-VAL
          O_F_EXT_HAT_K
          K_F_EXT_HAT_K-VAL
          K_F_EXT_HAT_K
          O_DP_EE_D-VAL
          O_DP_EE_D
          O_T_EE_C-VAL
          O_T_EE_C
          O_DP_EE_C-VAL
          O_DP_EE_C
          O_DDP_EE_C-VAL
          O_DDP_EE_C
          THETA-VAL
          THETA
          DTHETA-VAL
          DTHETA
          CURRENT_ERRORS-VAL
          CURRENT_ERRORS
          LAST_MOTION_ERRORS-VAL
          LAST_MOTION_ERRORS
          CONTROL_COMMAND_SUCCESS_RATE-VAL
          CONTROL_COMMAND_SUCCESS_RATE
          ROBOT_MODE-VAL
          ROBOT_MODE
          ROBOT_TIME-VAL
          ROBOT_TIME
          GRIPPER_WIDTH-VAL
          GRIPPER_WIDTH
          GRIPPER_MAX_WIDTH-VAL
          GRIPPER_MAX_WIDTH
          GRIPPER_IS_GRASPED-VAL
          GRIPPER_IS_GRASPED
          GRIPPER_TEMPERATURE-VAL
          GRIPPER_TEMPERATURE
          GRIPPER_TIME-VAL
          GRIPPER_TIME
          IS_FRESH-VAL
          IS_FRESH
))