// Auto-generated. Do not edit!

// (in-package franka_interface_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let ExecuteSkillActionGoal = require('./ExecuteSkillActionGoal.js');
let ExecuteSkillActionResult = require('./ExecuteSkillActionResult.js');
let ExecuteSkillActionFeedback = require('./ExecuteSkillActionFeedback.js');

//-----------------------------------------------------------

class ExecuteSkillAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new ExecuteSkillActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new ExecuteSkillActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new ExecuteSkillActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExecuteSkillAction
    // Serialize message field [action_goal]
    bufferOffset = ExecuteSkillActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = ExecuteSkillActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = ExecuteSkillActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExecuteSkillAction
    let len;
    let data = new ExecuteSkillAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = ExecuteSkillActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = ExecuteSkillActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = ExecuteSkillActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += ExecuteSkillActionGoal.getMessageSize(object.action_goal);
    length += ExecuteSkillActionResult.getMessageSize(object.action_result);
    length += ExecuteSkillActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'franka_interface_msgs/ExecuteSkillAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '360df2d730a050bb87c0a1345f21459c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    ExecuteSkillActionGoal action_goal
    ExecuteSkillActionResult action_result
    ExecuteSkillActionFeedback action_feedback
    
    ================================================================================
    MSG: franka_interface_msgs/ExecuteSkillActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    ExecuteSkillGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: franka_interface_msgs/ExecuteSkillGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint8 skill_type
    string skill_description
    uint8 meta_skill_type
    int64 meta_skill_id
    
    # Sensor topic to subscribe to
    string[] sensor_topics
    uint64[] sensor_value_sizes
    float64[] initial_sensor_values
    
    # traj gen
    uint8 trajectory_generator_type
    int32 trajectory_generator_param_data_size
    uint8[] trajectory_generator_param_data
    
    # fbc
    uint8 feedback_controller_type
    int32 feedback_controller_param_data_size
    uint8[] feedback_controller_param_data
    
    # termination
    uint8 termination_handler_type
    int32 termination_handler_param_data_size
    uint8[] termination_handler_param_data 
    
    # timer
    uint8 timer_type
    int32 num_timer_params
    uint8[] timer_params
    
    ================================================================================
    MSG: franka_interface_msgs/ExecuteSkillActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ExecuteSkillResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: franka_interface_msgs/ExecuteSkillResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result - happens when the skill terminates
    uint64 num_execution_result
    uint8[] execution_result
    
    ================================================================================
    MSG: franka_interface_msgs/ExecuteSkillActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    ExecuteSkillFeedback feedback
    
    ================================================================================
    MSG: franka_interface_msgs/ExecuteSkillFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback message - happens during skill execution 
    uint64 num_execution_feedback
    uint8[] execution_feedback
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExecuteSkillAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = ExecuteSkillActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new ExecuteSkillActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = ExecuteSkillActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new ExecuteSkillActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = ExecuteSkillActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new ExecuteSkillActionFeedback()
    }

    return resolved;
    }
};

module.exports = ExecuteSkillAction;
