// Generated by gencpp from file franka_interface_msgs/ExecuteSkillResult.msg
// DO NOT EDIT!


#ifndef FRANKA_INTERFACE_MSGS_MESSAGE_EXECUTESKILLRESULT_H
#define FRANKA_INTERFACE_MSGS_MESSAGE_EXECUTESKILLRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_interface_msgs
{
template <class ContainerAllocator>
struct ExecuteSkillResult_
{
  typedef ExecuteSkillResult_<ContainerAllocator> Type;

  ExecuteSkillResult_()
    : num_execution_result(0)
    , execution_result()  {
    }
  ExecuteSkillResult_(const ContainerAllocator& _alloc)
    : num_execution_result(0)
    , execution_result(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _num_execution_result_type;
  _num_execution_result_type num_execution_result;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _execution_result_type;
  _execution_result_type execution_result;





  typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteSkillResult_

typedef ::franka_interface_msgs::ExecuteSkillResult_<std::allocator<void> > ExecuteSkillResult;

typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillResult > ExecuteSkillResultPtr;
typedef boost::shared_ptr< ::franka_interface_msgs::ExecuteSkillResult const> ExecuteSkillResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator1> & lhs, const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator2> & rhs)
{
  return lhs.num_execution_result == rhs.num_execution_result &&
    lhs.execution_result == rhs.execution_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator1> & lhs, const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace franka_interface_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e5d113ae1195e7cbc619ec49d1ebaab";
  }

  static const char* value(const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e5d113ae1195e7cULL;
  static const uint64_t static_value2 = 0xbc619ec49d1ebaabULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_interface_msgs/ExecuteSkillResult";
  }

  static const char* value(const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Result - happens when the skill terminates\n"
"uint64 num_execution_result\n"
"uint8[] execution_result\n"
;
  }

  static const char* value(const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_execution_result);
      stream.next(m.execution_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteSkillResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::franka_interface_msgs::ExecuteSkillResult_<ContainerAllocator>& v)
  {
    s << indent << "num_execution_result: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.num_execution_result);
    s << indent << "execution_result[]" << std::endl;
    for (size_t i = 0; i < v.execution_result.size(); ++i)
    {
      s << indent << "  execution_result[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.execution_result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_INTERFACE_MSGS_MESSAGE_EXECUTESKILLRESULT_H
