// Generated by gencpp from file franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmd.msg
// DO NOT EDIT!


#ifndef FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTFRANKAINTERFACESTATUSCMD_H
#define FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTFRANKAINTERFACESTATUSCMD_H

#include <ros/service_traits.h>


#include <franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmdRequest.h>
#include <franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmdResponse.h>


namespace franka_interface_msgs
{

struct GetCurrentFrankaInterfaceStatusCmd
{

typedef GetCurrentFrankaInterfaceStatusCmdRequest Request;
typedef GetCurrentFrankaInterfaceStatusCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentFrankaInterfaceStatusCmd
} // namespace franka_interface_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd > {
  static const char* value()
  {
    return "1d3fe55393993751ebdd77c7f87c1d1e";
  }

  static const char* value(const ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd&) { return value(); }
};

template<>
struct DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd > {
  static const char* value()
  {
    return "franka_interface_msgs/GetCurrentFrankaInterfaceStatusCmd";
  }

  static const char* value(const ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd&) { return value(); }
};


// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdRequest> should match
// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >
template<>
struct MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdRequest> should match
// service_traits::DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >
template<>
struct DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdRequest>
{
  static const char* value()
  {
    return DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdResponse> should match
// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >
template<>
struct MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdResponse> should match
// service_traits::DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >
template<>
struct DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdResponse>
{
  static const char* value()
  {
    return DataType< ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentFrankaInterfaceStatusCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTFRANKAINTERFACESTATUSCMD_H
