// Generated by gencpp from file franka_interface_msgs/GetCurrentRobotStateCmdRequest.msg
// DO NOT EDIT!


#ifndef FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTROBOTSTATECMDREQUEST_H
#define FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTROBOTSTATECMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace franka_interface_msgs
{
template <class ContainerAllocator>
struct GetCurrentRobotStateCmdRequest_
{
  typedef GetCurrentRobotStateCmdRequest_<ContainerAllocator> Type;

  GetCurrentRobotStateCmdRequest_()
    {
    }
  GetCurrentRobotStateCmdRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCurrentRobotStateCmdRequest_

typedef ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<std::allocator<void> > GetCurrentRobotStateCmdRequest;

typedef boost::shared_ptr< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest > GetCurrentRobotStateCmdRequestPtr;
typedef boost::shared_ptr< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest const> GetCurrentRobotStateCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace franka_interface_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "franka_interface_msgs/GetCurrentRobotStateCmdRequest";
  }

  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCurrentRobotStateCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::franka_interface_msgs::GetCurrentRobotStateCmdRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTROBOTSTATECMDREQUEST_H
