// Generated by gencpp from file franka_interface_msgs/GetCurrentRobotStateCmd.msg
// DO NOT EDIT!


#ifndef FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTROBOTSTATECMD_H
#define FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTROBOTSTATECMD_H

#include <ros/service_traits.h>


#include <franka_interface_msgs/GetCurrentRobotStateCmdRequest.h>
#include <franka_interface_msgs/GetCurrentRobotStateCmdResponse.h>


namespace franka_interface_msgs
{

struct GetCurrentRobotStateCmd
{

typedef GetCurrentRobotStateCmdRequest Request;
typedef GetCurrentRobotStateCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCurrentRobotStateCmd
} // namespace franka_interface_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmd > {
  static const char* value()
  {
    return "b518dbe0aba9b1925588d18e42fb85fa";
  }

  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmd&) { return value(); }
};

template<>
struct DataType< ::franka_interface_msgs::GetCurrentRobotStateCmd > {
  static const char* value()
  {
    return "franka_interface_msgs/GetCurrentRobotStateCmd";
  }

  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmd&) { return value(); }
};


// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest> should match
// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmd >
template<>
struct MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest> should match
// service_traits::DataType< ::franka_interface_msgs::GetCurrentRobotStateCmd >
template<>
struct DataType< ::franka_interface_msgs::GetCurrentRobotStateCmdRequest>
{
  static const char* value()
  {
    return DataType< ::franka_interface_msgs::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmdResponse> should match
// service_traits::MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmd >
template<>
struct MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_interface_msgs::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_interface_msgs::GetCurrentRobotStateCmdResponse> should match
// service_traits::DataType< ::franka_interface_msgs::GetCurrentRobotStateCmd >
template<>
struct DataType< ::franka_interface_msgs::GetCurrentRobotStateCmdResponse>
{
  static const char* value()
  {
    return DataType< ::franka_interface_msgs::GetCurrentRobotStateCmd >::value();
  }
  static const char* value(const ::franka_interface_msgs::GetCurrentRobotStateCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_INTERFACE_MSGS_MESSAGE_GETCURRENTROBOTSTATECMD_H
