// Auto-generated. Do not edit!

// (in-package franka_interface_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ExecuteSkillResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.num_execution_result = null;
      this.execution_result = null;
    }
    else {
      if (initObj.hasOwnProperty('num_execution_result')) {
        this.num_execution_result = initObj.num_execution_result
      }
      else {
        this.num_execution_result = 0;
      }
      if (initObj.hasOwnProperty('execution_result')) {
        this.execution_result = initObj.execution_result
      }
      else {
        this.execution_result = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ExecuteSkillResult
    // Serialize message field [num_execution_result]
    bufferOffset = _serializer.uint64(obj.num_execution_result, buffer, bufferOffset);
    // Serialize message field [execution_result]
    bufferOffset = _arraySerializer.uint8(obj.execution_result, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ExecuteSkillResult
    let len;
    let data = new ExecuteSkillResult(null);
    // Deserialize message field [num_execution_result]
    data.num_execution_result = _deserializer.uint64(buffer, bufferOffset);
    // Deserialize message field [execution_result]
    data.execution_result = _arrayDeserializer.uint8(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.execution_result.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'franka_interface_msgs/ExecuteSkillResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0e5d113ae1195e7cbc619ec49d1ebaab';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result - happens when the skill terminates
    uint64 num_execution_result
    uint8[] execution_result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ExecuteSkillResult(null);
    if (msg.num_execution_result !== undefined) {
      resolved.num_execution_result = msg.num_execution_result;
    }
    else {
      resolved.num_execution_result = 0
    }

    if (msg.execution_result !== undefined) {
      resolved.execution_result = msg.execution_result;
    }
    else {
      resolved.execution_result = []
    }

    return resolved;
    }
};

module.exports = ExecuteSkillResult;
