# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from franka_interface_msgs/SensorDataGroup.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import franka_interface_msgs.msg
import std_msgs.msg

class SensorDataGroup(genpy.Message):
  _md5sum = "859c186ac0046509397a685ba0f2e8d2"
  _type = "franka_interface_msgs/SensorDataGroup"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# SensorDataGroup
std_msgs/Header header
bool has_trajectory_generator_sensor_data
bool has_feedback_controller_sensor_data
bool has_termination_handler_sensor_data
SensorData trajectoryGeneratorSensorData
SensorData feedbackControllerSensorData
SensorData terminationHandlerSensorData
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: franka_interface_msgs/SensorData
# Sensor data
std_msgs/Header header
string info
uint8 type
int32 size
uint8[] sensorData"""
  __slots__ = ['header','has_trajectory_generator_sensor_data','has_feedback_controller_sensor_data','has_termination_handler_sensor_data','trajectoryGeneratorSensorData','feedbackControllerSensorData','terminationHandlerSensorData']
  _slot_types = ['std_msgs/Header','bool','bool','bool','franka_interface_msgs/SensorData','franka_interface_msgs/SensorData','franka_interface_msgs/SensorData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,has_trajectory_generator_sensor_data,has_feedback_controller_sensor_data,has_termination_handler_sensor_data,trajectoryGeneratorSensorData,feedbackControllerSensorData,terminationHandlerSensorData

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorDataGroup, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.has_trajectory_generator_sensor_data is None:
        self.has_trajectory_generator_sensor_data = False
      if self.has_feedback_controller_sensor_data is None:
        self.has_feedback_controller_sensor_data = False
      if self.has_termination_handler_sensor_data is None:
        self.has_termination_handler_sensor_data = False
      if self.trajectoryGeneratorSensorData is None:
        self.trajectoryGeneratorSensorData = franka_interface_msgs.msg.SensorData()
      if self.feedbackControllerSensorData is None:
        self.feedbackControllerSensorData = franka_interface_msgs.msg.SensorData()
      if self.terminationHandlerSensorData is None:
        self.terminationHandlerSensorData = franka_interface_msgs.msg.SensorData()
    else:
      self.header = std_msgs.msg.Header()
      self.has_trajectory_generator_sensor_data = False
      self.has_feedback_controller_sensor_data = False
      self.has_termination_handler_sensor_data = False
      self.trajectoryGeneratorSensorData = franka_interface_msgs.msg.SensorData()
      self.feedbackControllerSensorData = franka_interface_msgs.msg.SensorData()
      self.terminationHandlerSensorData = franka_interface_msgs.msg.SensorData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B3I().pack(_x.has_trajectory_generator_sensor_data, _x.has_feedback_controller_sensor_data, _x.has_termination_handler_sensor_data, _x.trajectoryGeneratorSensorData.header.seq, _x.trajectoryGeneratorSensorData.header.stamp.secs, _x.trajectoryGeneratorSensorData.header.stamp.nsecs))
      _x = self.trajectoryGeneratorSensorData.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.trajectoryGeneratorSensorData.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.trajectoryGeneratorSensorData.type, _x.trajectoryGeneratorSensorData.size))
      _x = self.trajectoryGeneratorSensorData.sensorData
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.feedbackControllerSensorData.header.seq, _x.feedbackControllerSensorData.header.stamp.secs, _x.feedbackControllerSensorData.header.stamp.nsecs))
      _x = self.feedbackControllerSensorData.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.feedbackControllerSensorData.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.feedbackControllerSensorData.type, _x.feedbackControllerSensorData.size))
      _x = self.feedbackControllerSensorData.sensorData
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.terminationHandlerSensorData.header.seq, _x.terminationHandlerSensorData.header.stamp.secs, _x.terminationHandlerSensorData.header.stamp.nsecs))
      _x = self.terminationHandlerSensorData.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.terminationHandlerSensorData.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.terminationHandlerSensorData.type, _x.terminationHandlerSensorData.size))
      _x = self.terminationHandlerSensorData.sensorData
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.trajectoryGeneratorSensorData is None:
        self.trajectoryGeneratorSensorData = franka_interface_msgs.msg.SensorData()
      if self.feedbackControllerSensorData is None:
        self.feedbackControllerSensorData = franka_interface_msgs.msg.SensorData()
      if self.terminationHandlerSensorData is None:
        self.terminationHandlerSensorData = franka_interface_msgs.msg.SensorData()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.has_trajectory_generator_sensor_data, _x.has_feedback_controller_sensor_data, _x.has_termination_handler_sensor_data, _x.trajectoryGeneratorSensorData.header.seq, _x.trajectoryGeneratorSensorData.header.stamp.secs, _x.trajectoryGeneratorSensorData.header.stamp.nsecs,) = _get_struct_3B3I().unpack(str[start:end])
      self.has_trajectory_generator_sensor_data = bool(self.has_trajectory_generator_sensor_data)
      self.has_feedback_controller_sensor_data = bool(self.has_feedback_controller_sensor_data)
      self.has_termination_handler_sensor_data = bool(self.has_termination_handler_sensor_data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectoryGeneratorSensorData.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trajectoryGeneratorSensorData.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectoryGeneratorSensorData.info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trajectoryGeneratorSensorData.info = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.trajectoryGeneratorSensorData.type, _x.trajectoryGeneratorSensorData.size,) = _get_struct_Bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.trajectoryGeneratorSensorData.sensorData = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.feedbackControllerSensorData.header.seq, _x.feedbackControllerSensorData.header.stamp.secs, _x.feedbackControllerSensorData.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedbackControllerSensorData.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedbackControllerSensorData.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedbackControllerSensorData.info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedbackControllerSensorData.info = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.feedbackControllerSensorData.type, _x.feedbackControllerSensorData.size,) = _get_struct_Bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.feedbackControllerSensorData.sensorData = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.terminationHandlerSensorData.header.seq, _x.terminationHandlerSensorData.header.stamp.secs, _x.terminationHandlerSensorData.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.terminationHandlerSensorData.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.terminationHandlerSensorData.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.terminationHandlerSensorData.info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.terminationHandlerSensorData.info = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.terminationHandlerSensorData.type, _x.terminationHandlerSensorData.size,) = _get_struct_Bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.terminationHandlerSensorData.sensorData = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B3I().pack(_x.has_trajectory_generator_sensor_data, _x.has_feedback_controller_sensor_data, _x.has_termination_handler_sensor_data, _x.trajectoryGeneratorSensorData.header.seq, _x.trajectoryGeneratorSensorData.header.stamp.secs, _x.trajectoryGeneratorSensorData.header.stamp.nsecs))
      _x = self.trajectoryGeneratorSensorData.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.trajectoryGeneratorSensorData.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.trajectoryGeneratorSensorData.type, _x.trajectoryGeneratorSensorData.size))
      _x = self.trajectoryGeneratorSensorData.sensorData
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.feedbackControllerSensorData.header.seq, _x.feedbackControllerSensorData.header.stamp.secs, _x.feedbackControllerSensorData.header.stamp.nsecs))
      _x = self.feedbackControllerSensorData.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.feedbackControllerSensorData.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.feedbackControllerSensorData.type, _x.feedbackControllerSensorData.size))
      _x = self.feedbackControllerSensorData.sensorData
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.terminationHandlerSensorData.header.seq, _x.terminationHandlerSensorData.header.stamp.secs, _x.terminationHandlerSensorData.header.stamp.nsecs))
      _x = self.terminationHandlerSensorData.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.terminationHandlerSensorData.info
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bi().pack(_x.terminationHandlerSensorData.type, _x.terminationHandlerSensorData.size))
      _x = self.terminationHandlerSensorData.sensorData
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.trajectoryGeneratorSensorData is None:
        self.trajectoryGeneratorSensorData = franka_interface_msgs.msg.SensorData()
      if self.feedbackControllerSensorData is None:
        self.feedbackControllerSensorData = franka_interface_msgs.msg.SensorData()
      if self.terminationHandlerSensorData is None:
        self.terminationHandlerSensorData = franka_interface_msgs.msg.SensorData()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.has_trajectory_generator_sensor_data, _x.has_feedback_controller_sensor_data, _x.has_termination_handler_sensor_data, _x.trajectoryGeneratorSensorData.header.seq, _x.trajectoryGeneratorSensorData.header.stamp.secs, _x.trajectoryGeneratorSensorData.header.stamp.nsecs,) = _get_struct_3B3I().unpack(str[start:end])
      self.has_trajectory_generator_sensor_data = bool(self.has_trajectory_generator_sensor_data)
      self.has_feedback_controller_sensor_data = bool(self.has_feedback_controller_sensor_data)
      self.has_termination_handler_sensor_data = bool(self.has_termination_handler_sensor_data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectoryGeneratorSensorData.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trajectoryGeneratorSensorData.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.trajectoryGeneratorSensorData.info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.trajectoryGeneratorSensorData.info = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.trajectoryGeneratorSensorData.type, _x.trajectoryGeneratorSensorData.size,) = _get_struct_Bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.trajectoryGeneratorSensorData.sensorData = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.feedbackControllerSensorData.header.seq, _x.feedbackControllerSensorData.header.stamp.secs, _x.feedbackControllerSensorData.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedbackControllerSensorData.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedbackControllerSensorData.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.feedbackControllerSensorData.info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.feedbackControllerSensorData.info = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.feedbackControllerSensorData.type, _x.feedbackControllerSensorData.size,) = _get_struct_Bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.feedbackControllerSensorData.sensorData = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.terminationHandlerSensorData.header.seq, _x.terminationHandlerSensorData.header.stamp.secs, _x.terminationHandlerSensorData.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.terminationHandlerSensorData.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.terminationHandlerSensorData.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.terminationHandlerSensorData.info = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.terminationHandlerSensorData.info = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.terminationHandlerSensorData.type, _x.terminationHandlerSensorData.size,) = _get_struct_Bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.terminationHandlerSensorData.sensorData = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B3I = None
def _get_struct_3B3I():
    global _struct_3B3I
    if _struct_3B3I is None:
        _struct_3B3I = struct.Struct("<3B3I")
    return _struct_3B3I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bi = None
def _get_struct_Bi():
    global _struct_Bi
    if _struct_Bi is None:
        _struct_Bi = struct.Struct("<Bi")
    return _struct_Bi
